[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "graxon"
version = "0.0.1"
description = "Placeholder release to reserve the graxon package name."
readme = "README.md"
requires-python = ">=3.8"
dynamic = ["dependencies"]
license = { text = "MIT" }
authors = [
    { name = "Vipin Kumawat", email = "kumawatvipin066@gmail.com" }
]
classifiers = [
    "Development Status :: 1 - Planning",
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
Homepage = "https://github.com/Graxon-rag/graxon"
Issues = "https://github.com/Graxon-rag/graxon/issues"

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.dynamic]
dependencies = {file = ["requirements.txt"]}
